[package]
name = "type-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0.26"
console = "0.15.3"
glob = "0.3.0"
rand = "0.8.5"
code-lines = { git = "https://github.com/NilVentosa/code-lines" }
